language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - master
  - nightly

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer install

script:
  - ./vendor/bin/phpunit